### ISSUE TITLE
"providerStatus" undefined error when fetching clusters

### ISSUE THREAD

**Issue by msa0311** [Mirantis/lens-extension-cc#95]
When Testing the lens-extension-cc with Lens 4.1.0 alpha release I figured out that there is an uncaught error thrown when fetching the clusters from container cloud:

```
ClustersProvider.js?3e90:136 [@mirantis/lens-extension-cc/ClustersProvider._deserializeClustersList()] ERROR with cluster 0: Cannot read property 'providerStatus' of undefined TypeError: Cannot read property 'providerStatus' of undefined
    at getServerUrl (Cluster.js?8f07:10)
    at new Cluster (Cluster.js?8f07:93)
    at eval (ClustersProvider.js?3e90:133)
    at Array.map (<anonymous>)
    at _deserializeClustersList (ClustersProvider.js?3e90:131)
    at eval (ClustersProvider.js?3e90:190)
    at Array.every (<anonymous>)
    at _fetchClusters (ClustersProvider.js?3e90:189)
    at async _loadData (ClustersProvider.js?3e90:223)
```

Not sure if its really depending on changes introduced with Lens 4.1.0 or has been there before.
Issue seems not to be a blocker for using the Extension. Everything seems to work fine for the user.  

OS: MacOS 10.14.6 (Mojave)

**Comment by stefcameron** [comment]
@msa0311 Thanks for reporting this, however, I'm unable to reproduce this in my testing with Lens `4.1.0-alpha.1`. The error is being caught, though. It shouldn't be uncaught causing a crash in the extension. It's just being reported in the console (maybe I shouldn't do that, but then it would just be silently ignored...). That cluster will get ignored and won't show-up in the list. (FYI, I improved the error message a bit to include the namespace and name of the cluster, not just its index in the list, https://github.com/Mirantis/lens-extension-cc/commit/dbcd4f80a5e4f44f497138f3836417a812a6fb98)

That error you're seeing is coming from https://github.com/Mirantis/lens-extension-cc/blob/master/src/cc/store/Cluster.js#L10

Without `status.providerStatus`, the extension can't read `status.providerStatus.loadBalancerHost` in order to generate the server URL it uses when it configures the cluster in the kubeConfig: https://github.com/Mirantis/lens-extension-cc/blob/master/src/cc/templates.js#L27

Is there another way to get the host from the cluster metadata obtained from a Mirantis Container Cloud instance?

**Comment by msa0311** [comment]
@stefcameron sorry, my mistake! You are right, its properly caught and what I've mentioned is the the error output from the "ClustersProvider.js: _deserializeClustersList()". 

https://github.com/Mirantis/lens-extension-cc/blob/dbcd4f80a5e4f44f497138f3836417a812a6fb98/src/cc/store/ClustersProvider.js#L124

No idea if there is a "better" way to do this...  Maybe try asking in #lens-hq!

**Comment by stefcameron** [comment]
> No idea if there is a "better" way to do this... Maybe try asking in #lens-hq!

Thanks for having another look. I'll ask around and see if there's an alternate way to get the host, or if there's a valid reason why that property wouldn't be set (and so I just silently ignore those clusters instead of blindly trying to access the nested property, triggering the exception).

**Comment by stefcameron** [comment]
I confirmed with the MCC team I'm looking at the correct properties, but I know more of what to look for to know if a cluster isn't ready yet (i.e. still being provisioned) and therefore cannot be added.
